
import React, { useState, useEffect } from 'react';
import Layout from './components/Layout';
import ToolCard from './components/ToolCard';
import AnalysisResultView from './components/AnalysisResultView';
import { ToolType, AnalysisResult, Language, FileInfo } from './types';
import { analyzeContent } from './services/geminiService';

const App: React.FC = () => {
  const [lang, setLang] = useState<Language>('ar');
  const [selectedTool, setSelectedTool] = useState<ToolType | null>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [inputText, setInputText] = useState('');
  const [fileInfo, setFileInfo] = useState<FileInfo | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<'upload' | 'url'>('upload');

  const isAr = lang === 'ar';

  const tools = [
    {
      type: ToolType.FAKE_NEWS,
      title: isAr ? "محلل الأخبار الزائفة" : "Fake News Analyzer",
      description: isAr ? "تحقق من النصوص أو الروابط الإخبارية لكشف التضليل والشائعات." : "Verify news text or links to detect misinformation and rumors.",
      iconBg: "bg-amber-500/20 border border-amber-500/30",
      icon: <svg className="h-10 w-10 text-amber-500" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="2" y="2" width="20" height="20" rx="2"/><line x1="7" y1="8" x2="17" y2="8"/><line x1="7" y1="12" x2="17" y2="12"/><line x1="7" y1="16" x2="13" y2="16"/></svg>
    },
    {
      type: ToolType.MALWARE,
      title: isAr ? "فاحص الملفات الخبيثة" : "Malicious File Scanner",
      description: isAr ? "افحص الملفات أو تأكد من سلامة الروابط البرمجية والبرمجيات." : "Scan files or verify the safety of software links and scripts.",
      iconBg: "bg-emerald-500/20 border border-emerald-500/30",
      icon: <svg className="h-10 w-10 text-emerald-500" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/></svg>
    },
    {
      type: ToolType.DEEPFAKE,
      title: isAr ? "كاشف المحتوى المزيف" : "Deepfake Detector",
      description: isAr ? "حلل الصور والروابط للكشف عن علامات التزييف العميق المولد بالذكاء الاصطناعي." : "Analyze media and links to detect deepfake signs generated by AI.",
      iconBg: "bg-violet-500/20 border border-violet-500/30",
      icon: <svg className="h-10 w-10 text-violet-500" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M18 21a6 6 0 0 0-12 0"/><circle cx="12" cy="9" r="4"/><path d="M12 18v2"/></svg>
    }
  ];

  const handleStartAnalysis = async () => {
    if (!selectedTool || (!inputText.trim() && !fileInfo)) return;
    setIsAnalyzing(true);
    setError(null);
    try {
      const data = await analyzeContent(selectedTool, inputText, lang);
      setResult(data);
    } catch (err) {
      setError(isAr ? "حدث خطأ في النظام. يرجى المحاولة لاحقاً." : "System error. Please try again later.");
    } finally {
      setIsAnalyzing(false);
    }
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      setFileInfo({
        name: file.name,
        type: file.type || 'file',
        size: (file.size / 1024 / 1024).toFixed(2) + ' MB',
      });
      const reader = new FileReader();
      reader.onload = (event) => setInputText(event.target?.result as string || file.name);
      reader.readAsText(file);
    }
  };

  const reset = () => {
    setResult(null);
    setInputText('');
    setFileInfo(null);
    setError(null);
  };

  useEffect(() => {
    if (selectedTool === ToolType.FAKE_NEWS) {
      setActiveTab('url');
    } else {
      setActiveTab('upload');
    }
  }, [selectedTool]);

  const renderToolInput = () => {
    const tool = tools.find(t => t.type === selectedTool);
    const hasTabs = selectedTool === ToolType.MALWARE || selectedTool === ToolType.DEEPFAKE;
    const isUpload = (hasTabs && activeTab === 'upload');
    const isTextOnly = selectedTool === ToolType.FAKE_NEWS;

    return (
      <div className="max-w-4xl mx-auto space-y-12 animate-in fade-in duration-500 w-full py-8">
        <div className="text-center space-y-4">
          <h2 className="text-4xl font-bold text-white tracking-tight">{tool?.title}</h2>
          <p className="text-slate-400 text-lg font-medium opacity-80 leading-relaxed">
            {selectedTool === ToolType.FAKE_NEWS
              ? (isAr ? "أدخل نص الخبر أو الرابط للتحقق من المصداقية باستخدام بحث جوجل." : "Enter news text or link to verify authenticity using Google Search.")
              : (isAr ? "اختر الطريقة المفضلة (ملف أو رابط) لبدء الفحص الذكي وكشف التهديدات." : "Choose preferred method (File or Link) to start smart scan and threat detection.")}
          </p>
        </div>

        {hasTabs && (
          <div className="flex justify-center">
            <div className="flex bg-[#1b222d] p-1.5 rounded-2xl border border-slate-800">
              <button 
                onClick={() => {setActiveTab('upload'); reset();}} 
                className={`px-8 py-2.5 rounded-xl text-sm font-bold transition-all ${activeTab === 'upload' ? 'bg-indigo-600 text-white shadow-lg' : 'text-slate-500 hover:text-white'}`}
              >
                {isAr ? 'فحص ملف' : 'File Scan'}
              </button>
              <button 
                onClick={() => {setActiveTab('url'); reset();}} 
                className={`px-8 py-2.5 rounded-xl text-sm font-bold transition-all ${activeTab === 'url' ? 'bg-indigo-600 text-white shadow-lg' : 'text-slate-500 hover:text-white'}`}
              >
                {isAr ? 'فحص رابط' : 'Link Scan'}
              </button>
            </div>
          </div>
        )}

        <div className="space-y-6">
          {isUpload ? (
            <div className="w-full">
              {!fileInfo ? (
                <label className="group block w-full h-64 bg-[#1b222d]/40 border-2 border-dashed border-slate-700/60 hover:border-indigo-500/50 rounded-3xl cursor-pointer transition-all flex flex-col items-center justify-center space-y-4">
                  <input type="file" className="hidden" onChange={handleFileUpload} />
                  <div className="p-4 bg-indigo-500/10 rounded-2xl text-indigo-400 group-hover:scale-110 transition-transform">
                    <svg className="h-10 w-10" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12" />
                    </svg>
                  </div>
                  <div className="text-center">
                    <p className="text-xl font-bold text-white">{isAr ? 'اسحب الملف هنا أو انقر للاختيار' : 'Drag file here or click to browse'}</p>
                    <p className="text-slate-500 font-medium text-sm mt-1">{isAr ? 'يدعم الملفات النصية، المستندات، والبرمجيات' : 'Supports text, docs, and script files'}</p>
                  </div>
                </label>
              ) : (
                <div className="bg-[#1b222d] border border-slate-800 rounded-3xl p-8 flex flex-col items-center gap-6 shadow-xl">
                   <div className="text-5xl">📁</div>
                   <div className="text-center">
                     <p className="text-xl font-bold text-white truncate max-w-md">{fileInfo.name}</p>
                     <p className="text-slate-500 text-xs font-bold uppercase tracking-wider mt-1">{fileInfo.size}</p>
                   </div>
                   <div className="flex gap-4 w-full max-w-sm">
                     <button onClick={reset} disabled={isAnalyzing} className="flex-1 py-3 bg-slate-900 hover:bg-slate-800 text-white rounded-xl font-bold transition-all border border-slate-800">{isAr ? 'إلغاء' : 'Cancel'}</button>
                     <button onClick={handleStartAnalysis} disabled={isAnalyzing} className="flex-[2] py-3 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl font-bold shadow-lg transition-all active:scale-95">
                        {isAnalyzing ? (isAr ? 'جاري التحليل...' : 'Analyzing...') : (isAr ? 'بدء التحليل' : 'Start Analysis')}
                     </button>
                   </div>
                </div>
              )}
            </div>
          ) : (
            <div className="flex flex-col md:flex-row gap-4 items-stretch">
              <input 
                type="text" 
                value={inputText} 
                onChange={(e) => setInputText(e.target.value)} 
                placeholder={isTextOnly ? (isAr ? "أدخل الخبر أو الرابط..." : "Enter news or link...") : (isAr ? "أدخل الرابط المراد فحصه..." : "Enter URL to scan...")} 
                className={`flex-grow bg-[#1b222d] border border-slate-800 rounded-2xl px-6 py-4 text-lg text-white outline-none focus:border-indigo-500/50 transition-all font-semibold shadow-inner ${isAr ? 'text-right' : 'text-left'}`} 
                dir="auto"
              />
              <button 
                onClick={handleStartAnalysis} 
                disabled={isAnalyzing || !inputText.trim()} 
                className="px-10 py-4 bg-indigo-600 hover:bg-indigo-500 disabled:bg-slate-800 text-white text-lg font-bold rounded-2xl transition-all shadow-lg shadow-indigo-600/20 flex items-center justify-center gap-3 active:scale-95"
              >
                {isAnalyzing && (
                   <div className="w-5 h-5 border-2 border-white/20 border-t-white rounded-full animate-spin"></div>
                )}
                <span>{isAnalyzing ? (isAr ? 'جاري...' : 'Wait...') : (isAr ? 'فحص الآن' : 'Scan Now')}</span>
              </button>
            </div>
          )}
        </div>
        
        {error && <p className="text-rose-400 font-bold text-center bg-rose-500/10 py-4 rounded-xl border border-rose-500/20">{error}</p>}
      </div>
    );
  };

  return (
    <Layout lang={lang} setLang={setLang} showBack={!!selectedTool} onBack={() => {setSelectedTool(null); reset();}}>
      {!selectedTool ? (
        <div className="space-y-16 py-8 w-full">
          <h3 className="text-3xl font-bold text-center text-white tracking-tight">{isAr ? 'اختر الأداة المناسبة لبدء الفحص' : 'Choose a Tool to Start Scanning'}</h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8 w-full max-w-6xl mx-auto items-stretch">
            {tools.map(t => (
              <ToolCard key={t.type} {...t} onClick={setSelectedTool} />
            ))}
          </div>
        </div>
      ) : (
        <div className="py-4 w-full">{!result ? renderToolInput() : <AnalysisResultView result={result} onReset={reset} lang={lang} />}</div>
      )}
    </Layout>
  );
};

export default App;
